# Generated by Django 6.1.1 on 2026-09-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serveur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse_ip', models.GenericIPAddressField()),
                ('statut', models.CharField(choices=[('EN_LIGNE', 'En Ligne'), ('HORS_LIGNE', 'Hors Ligne'), ('MAINTENANCE', 'En Maintenance')], default='EN_LIGNE', max_length=20)),
                ('ram_utilisee', models.IntegerField(help_text='RAM utilisee en Go')),
            ],
        ),
    ]
